### ISSUE TITLE
A thin white line appears when the banner is downloaded.

### ISSUE THREAD

**Issue by debojyotichatterjee9** [liyasthomas/banner#4]
**A thin white line appears when the banner is downloaded.**
When I download a banner a thin white line appears in at the bottom of it.
Maybe its picking up some default background css I am not sure. This is much prominent on the darker shade of background colours.

**To Reproduce**
1. Go to 'https://liyasthomas.github.io/banner/'
2. Click on 'Randomize' or make your custom banner from the available options.
3. Click on 'Download'
4. Open the image from the downloaded location and you'll notice the line on the bottom.

**Expected behavior**
The background colour selected during customizing or using the 'Randomize' button should cover the banner background completely.

**Screenshots**
![banner (1)](https://user-images.githubusercontent.com/30823218/120112071-f8970e80-c191-11eb-9705-ee804282c702.png)
![banner (3)](https://user-images.githubusercontent.com/30823218/120112072-faf96880-c191-11eb-8947-544694b6d933.png)

**Desktop :**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome Version 91.0.4472.77

**Comment by izzqz** [comment]
The same thing happens in Windows and Edge. The issue is still relevant.

**Comment by liyasthomas** [comment]
Sorry for the issue you've faced. I'm not able to contribute to this project regularly because I'm working on multiple other projects. Feel free to open PR to fix the issue or please be patient until I switch to this project on a weekend.

Thanks for the patience.
